# Generated by Django 4.1.7 on 2023-05-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='view_counter',
            field=models.IntegerField(default=0),
        ),
    ]
